// Run with Playwright available in NODE_PATH; the local preview must be running.
const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const root=path.resolve(__dirname,'..'),data=JSON.parse(fs.readFileSync(path.join(root,'data/questions.json'))),byId=Object.fromEntries(data.questions.map(q=>[q.id,q]));
const URL='http://127.0.0.1:8765';const key='zhiti.demo.v1';const checks=[];let browser;
async function screenshot(page,name){await page.waitForFunction(()=>[...document.images].every(i=>i.complete&&i.naturalWidth>0));await page.screenshot({path:path.join(root,'screenshots',name),fullPage:true,animations:'disabled'});}
const pass=s=>{checks.push(s);console.log('PASS',s)};
(async()=>{browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage();const errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith(URL))external.push(r.url())});
const wait=async()=>{await page.waitForLoadState('networkidle');await page.locator('h1').waitFor()};const state=()=>page.evaluate(k=>JSON.parse(localStorage.getItem(k)),key);const nav=async name=>{await page.goto(URL+'/#'+name);await wait()};const overflow=async p=>assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
await page.goto(URL);await wait();assert.equal(await page.locator('.group-card').count(),6);assert.match(await page.locator('.stats').textContent(),/0/);await overflow(page);await screenshot(page,'desktop-home.png');pass('首页从零开始，6 个专项，桌面无横向溢出');
await nav('wrong');assert.equal(await page.locator('.empty').count(),1);await nav('favorites');assert.equal(await page.locator('.empty').count(),1);pass('错题与收藏初始空状态');
await nav('home');await page.locator('[data-start="图形推理"]').first().click();await page.locator('.question-panel').waitFor();const first=byId[data.groups[0].ids[0]];const incorrect='ABCD'.split('').find(x=>x!==first.answer);
assert.equal(await page.locator('.solution').count(),0);assert.equal(await page.locator('[data-action="submit"]').isDisabled(),true);
await page.locator('[data-choice="A"]').focus();await page.keyboard.press('Enter');assert.equal(await page.locator('[data-choice="A"]').getAttribute('aria-pressed'),'true');await page.locator(`[data-choice="${incorrect}"]`).click();await page.reload();await wait();assert.equal(await page.locator(`[data-choice="${incorrect}"]`).getAttribute('aria-pressed'),'true');await page.locator('[data-favorite]').click();await page.locator('[data-action="submit"]').click();assert.match(await page.locator('.result-line').textContent(),/错误/);assert.equal((await state()).attempts.length,1);await page.reload();await wait();assert.equal((await state()).attempts.length,1);await page.locator(`[data-choice="${first.answer}"]`).dispatchEvent('click');assert.equal((await state()).attempts.length,1);assert.equal((await state()).session.answers[first.id].choice,incorrect);await screenshot(page,'desktop-answer.png');pass('键盘选择、提交前改选、刷新保留选择与答案、答错入本、提交后不能改答');
await page.locator('[data-action="next"]').click();for(let i=1;i<5;i++){const q=byId[data.groups[0].ids[i]];assert.equal(await page.locator('.solution').count(),0);await page.locator(`[data-choice="${q.answer}"]`).click();await page.locator('[data-action="submit"]').click();await page.locator('[data-action="next"]').click();}
await page.locator('.summary-score').waitFor();assert.match(await page.locator('.summary-score').textContent(),/80/);assert.equal((await state()).attempts.length,5);pass('完整五题流程，4 对 1 错，小结正确率 80%');
await page.locator('[data-action="session-wrong"]').click();await page.locator(`[data-choice="${first.answer}"]`).click();await page.locator('[data-action="submit"]').click();await nav('wrong');assert.match(await page.locator('.pill').textContent(),/已订正/);await page.locator('[data-filter="pending"]').click();assert.equal(await page.locator('.empty').count(),1);await nav('favorites');assert.equal(await page.locator('.record').count(),1);await page.locator('[data-favorite]').click();assert.equal(await page.locator('.empty').count(),1);pass('错题订正保留历史，待复习筛选，收藏取消');
await nav('home');await page.locator('[data-action="reset"]').click();await page.locator('#cancel-reset').click();assert.ok((await state()).attempts.length);await page.locator('[data-action="reset"]').click();await page.locator('#confirm-reset').click();assert.equal((await state()).attempts.length,0);assert.equal((await state()).favorites.length,0);assert.equal(Object.keys((await state()).wrong).length,0);pass('清空记录必须确认；取消保留、确认归零');
// Exercise every remaining sample with rendered options, including both material groups.
for(const group of data.groups.slice(1)){await nav('home');await page.locator(`[data-start="${group.id}"]`).click();for(const id of group.ids){const q=byId[id];await page.locator('.question-panel').waitFor();assert.equal(await page.locator('.solution').count(),0);if(q.materialId)assert.equal(await page.locator('.material-panel').count(),1);await overflow(page);await page.locator(`[data-choice="${q.answer}"]`).click();await page.locator('[data-action="submit"]').click();assert.match(await page.locator('.result-line').textContent(),/正确/);await page.locator('[data-action="next"]').click();}await page.locator('.summary-score').waitFor();assert.match(await page.locator('.summary-score').textContent(),/100/);}
pass('其余 25 道题逐题作答、5 组小结及两个完整材料组');
for(const asset of data.assets){const r=await page.request.get(URL+'/assets/'+asset.name);assert.equal(r.status(),200)}pass('全部 86 张图片可由本地服务读取');
await nav('home');await page.locator('[data-start="180724"]').click();await page.locator('.material-panel').waitFor();await screenshot(page,'desktop-material.png');const img=page.locator('.material-panel img').first();await img.click();assert.equal(await page.locator('#image-dialog').isVisible(),true);await page.keyboard.press('Escape');assert.equal(await page.locator('#image-dialog').isVisible(),false);pass('资料分析分栏，配图放大和 Escape 关闭');
const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const mp=await mobile.newPage();await mp.goto(URL);await mp.waitForLoadState('networkidle');await overflow(mp);await screenshot(mp,'mobile-home.png');await mp.locator('[data-start="180724"]').click();await mp.locator('.material-panel').waitFor();await overflow(mp);await screenshot(mp,'mobile-material.png');await mp.locator('.material-panel summary').click();assert.equal(await mp.locator('.material-panel').getAttribute('open'),null);const mq=byId[data.groups[4].ids[0]];await mp.locator(`[data-choice="${mq.answer}"]`).click();await mp.locator('[data-action="submit"]').click();assert.equal(await mp.locator('.material-panel').getAttribute('open'),null);await overflow(mp);await screenshot(mp,'mobile-answer.png');pass('390px 手机首页、材料折叠、答案页面无横向溢出');
await mp.goto(URL+'/#home');await mp.locator('[data-start="定义判断"]').click();await mp.locator('.question-panel').waitFor();await overflow(mp);await screenshot(mp,'mobile-long-question.png');pass('手机长题干和长选项显示');
await page.evaluate(()=>document.documentElement.style.fontSize='200%');await overflow(page);await page.evaluate(()=>document.documentElement.style.fontSize='');pass('文字放大无页面横向溢出');
const blocked=await browser.newContext();await blocked.addInitScript(()=>{Storage.prototype.setItem=function(){throw new DOMException('quota','QuotaExceededError')}});const bp=await blocked.newPage();await bp.goto(URL);await bp.locator('[data-start="图形推理"]').first().click();await bp.locator('.question-panel').waitFor();assert.match(await bp.locator('.storage-warning').textContent(),/无法保存/);await bp.locator('[data-choice="A"]').click();await bp.locator('[data-action="submit"]').click();assert.equal(await bp.locator('.solution').count(),1);pass('存储写入失败显示持久提示，仍可答题');
const broken=await browser.newContext();await broken.route('**/assets/**',r=>r.abort());const ip=await broken.newPage();await ip.goto(URL);await ip.locator('[data-start="图形推理"]').first().click();await ip.locator('.image-error').first().waitFor();pass('图片加载失败有可读提示');
const supported=await page.evaluate(()=>!!document.modelContext?.registerTool);console.log('WebMCP native context:',supported?'available':'unavailable');assert.deepEqual(errors,[]);assert.deepEqual(external,[]);pass('无页面运行错误，运行过程无外网请求');
fs.writeFileSync(path.join(root,'TEST-RESULTS.md'),'# 本地验收结果\n\n'+checks.map(s=>'- 通过：'+s).join('\n')+'\n\nWebMCP：浏览器'+(supported?'具备接口；本次未进行原生调用验收。':'未提供原生上下文，注册与原生调用验收不可用；普通界面正常。')+'\n\n使用独立自动化浏览器，未写入用户预览窗口的练习记录。\n');await browser.close();})().catch(async e=>{console.error(e);if(browser)await browser.close();process.exit(1)});
