const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={grid:'M3 3h6v6H3z M15 3h6v6h-6z M3 15h6v6H3z M15 15h6v6h-6z',book:'M4 3h13a3 3 0 0 1 3 3v15H7a3 3 0 0 1-3-3V3z M4 17h16 M8 7h8 M8 11h6',star:'m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2-5.6-3-5.6 3 1.1-6.2L3 9.6l6.2-.9z',arrow:'M4 12h15 M13 6l6 6-6 6',check:'m5 12 4 4 10-10',chart:'M4 3v17h17 M8 16v-5 M13 16V7 M18 16V4',layers:'m12 3 9 5-9 5-9-5z M3 12l9 5 9-5 M3 16l9 5 9-5',logic:'M4 5h6v6H4z M15 14h6v6h-6z M10 8h7v6 M7 11v6h8',info:'M12 10v7 M12 6v1 M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0',clock:'M12 7v5l3 2 M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0'};
const icon=(name)=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name]||paths.book}" stroke-linecap="round" stroke-linejoin="round"/></svg>`;
const KEY='zhiti.demo.v1';const blank=()=>({version:1,attempts:[],favorites:[],wrong:{},session:null});
let state=blank(),db,byId,storageError='',listFilter='all',noticeTimer;
try{const stored=JSON.parse(localStorage.getItem(KEY));if(stored?.version===1&&Array.isArray(stored.attempts)&&Array.isArray(stored.favorites)&&stored.wrong&&typeof stored.wrong==='object')state=stored;}catch{storageError='浏览器中的记录无法读取。本次仍可练习，建议先检查浏览器存储设置。';}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{storageError='记录无法保存：浏览器存储不可用或空间不足。关闭页面后，本次进度可能丢失。';toast(storageError);}}
function toast(s){$('#notice').textContent=s;$('#notice').classList.add('visible');clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('#notice').classList.remove('visible'),4500);}
const current=()=>state.session?byId[state.session.ids[state.session.index]]:null;
const doneIds=()=>new Set(state.attempts.map(a=>a.qid));
const rate=arr=>arr.length?Math.round(arr.filter(a=>a.correct).length/arr.length*100):0;
function route(){return (location.hash.slice(1)||'home').split('/')[0];}
function go(name){if(route()!==name)location.hash=name;render();}
function footer(){return `<footer class="footnote"><a href="${db.repository}" target="_blank" rel="noopener">题库来源</a><button class="button text" data-action="reset">清空记录</button></footer>`;}
function frame(body){let page=route();return `<div class="shell"><aside class="sidebar"><a class="brand" href="#home"><span class="brand-mark">${icon('check')}</span>知题</a><nav class="nav" aria-label="主要导航"><a href="#home" class="${['home','quiz','summary'].includes(page)?'active':''}">${icon('grid')}专项<span class="count">30</span></a><a href="#wrong" class="${page==='wrong'?'active':''}">${icon('book')}错题<span class="count">${Object.keys(state.wrong).length}</span></a><a href="#favorites" class="${page==='favorites'?'active':''}">${icon('star')}收藏<span class="count">${state.favorites.length}</span></a></nav></aside><main class="main">${storageError?`<div class="storage-warning" role="alert">${esc(storageError)}</div>`:''}<div class="content">${body}${page==='home'?footer():''}</div></main></div>`;}
function home(){const unique=doneIds(),s=state.session;const active=s&&!s.completed;const cards=module=>db.groups.filter(g=>g.module===module).map(g=>`<article class="group-card"><h3>${esc(g.title)}</h3><div class="card-bottom"><span>${g.ids.filter(id=>unique.has(id)).length} / ${g.ids.length}</span><button data-start="${g.id}" aria-label="开始${esc(g.title)}练习">开始 ${icon('arrow')}</button></div></article>`).join('');return `<h1>专项练习</h1><section class="stats" aria-label="练习统计"><div class="stat"><div class="stat-label">已练</div><div class="stat-value">${unique.size}<span>/ 30</span></div></div><div class="stat"><div class="stat-label">正确率</div><div class="stat-value">${state.attempts.length?rate(state.attempts)+'%':'—'}</div></div><div class="stat"><div class="stat-label">待复习</div><div class="stat-value">${Object.values(state.wrong).filter(w=>!w.corrected).length}</div></div></section>${active?`<section class="resume"><div><h2>${esc(s.title)}</h2><p>${Object.keys(s.answers).length} / ${s.ids.length}</p></div><button class="button light" data-action="resume">继续 ${icon('arrow')}</button></section>`:''}<div class="section-heading"><h2>判断推理</h2><span>20 题</span></div><div class="group-grid">${cards('判断推理')}</div><div class="section-heading"><h2>资料分析</h2><span>10 题</span></div><div class="group-grid">${cards('资料分析')}</div>`;}
function start(ids,title){if(!Array.isArray(ids)||!ids.length||ids.some(id=>!byId[id]))throw Error('练习题目不存在');state.session={id:crypto.randomUUID(),title,ids:[...ids],index:0,answers:{},selected:null,materialOpen:true,completed:false};save();go('quiz');window.scrollTo(0,0);return {count:ids.length,title};}
function startGroup(id){const group=db.groups.find(g=>g.id===id);if(!group)throw Error('专项不存在');return start(group.ids,group.title);}
function solution(q,answer){return `<section class="solution" aria-label="答案与解析"><div class="result-line"><span class="result-symbol ${answer.correct?'':'wrong'}">${answer.correct?'✓':'×'}</span><div><h3>${answer.correct?'正确':'错误'}</h3><p>答案 ${q.answer} · 选择 ${answer.choice}</p></div></div><h3>解析</h3><div class="rich">${q.explanation}</div>${[['快速解法',q.fast],['推理步骤',q.reasoning],['易错点',q.pitfalls]].filter(x=>x[1]).map(([label,text])=>`<details><summary>${label}</summary><div class="extra-text">${esc(text)}</div></details>`).join('')}<p class="disclaimer"><a href="${q.source}" target="_blank" rel="noopener">原题 ↗</a></p></section>`;}
function quiz(){const s=state.session,q=current();if(!q)return empty('尚未选择专项','','grid');const answer=s.answers[q.id],saved=state.favorites.includes(q.id),m=db.materials.find(m=>m.id===q.materialId);return `<div class="quiz-header"><h1>${esc(s.title)}</h1><button class="button secondary" data-action="home">退出</button></div><div class="progress-meta"><span>${s.index+1} / ${s.ids.length}</span><span>已答 ${Object.keys(s.answers).length}</span></div><div class="progress" role="progressbar" aria-label="本组答题进度" aria-valuenow="${Object.keys(s.answers).length}" aria-valuemin="0" aria-valuemax="${s.ids.length}"><div style="width:${Object.keys(s.answers).length/s.ids.length*100}%"></div></div><div class="question-layout ${m?'with-material':''}">${m?`<details class="material-panel" ${s.materialOpen===false?'':'open'}><summary>材料</summary><div class="rich">${m.html}</div></details>`:''}<div><section class="question-panel"><div class="question-meta"><div class="source-meta">${esc(q.year)} ${esc(q.region)} · ${q.id}</div><button class="star-button ${saved?'saved':''}" data-favorite="${q.id}" aria-label="${saved?'取消收藏':'收藏本题'}" aria-pressed="${saved}">${icon('star')}</button></div><div class="rich stem">${q.stem}</div><div class="options" role="group" aria-label="答案选项">${q.options.map(o=>{let cls='',label='';if(answer){if(o.key===q.answer){cls='correct';label='正确';}else if(o.key===answer.choice){cls='incorrect';label='你的选择';}}else if(s.selected===o.key)cls='selected';return `<button class="option ${cls}" data-choice="${o.key}" aria-pressed="${(answer?.choice||s.selected)===o.key}" aria-disabled="${!!answer}"><span class="option-key">${o.key}</span><span class="option-content rich">${o.html}</span>${label?`<span class="option-status">${label}</span>`:''}</button>`;}).join('')}</div><div class="quiz-actions">${answer?`<button class="button" data-action="next">${s.index===s.ids.length-1?'查看结果':'下一题'} ${icon('arrow')}</button>`:`<button class="button" data-action="submit" ${s.selected?'':'disabled'}>提交 ${icon('check')}</button>`}</div></section>${answer?solution(q,answer):''}</div></div>`;}
function choose(choice){const q=current(),s=state.session;if(!q||s.completed||!q.options.some(o=>o.key===choice))throw Error('无效选项');if(s.answers[q.id])return {submitted:true};s.selected=choice;save();render();$(`[data-choice="${choice}"]`)?.focus({preventScroll:true});return {selected:choice};}
function submit(choice){const q=current(),s=state.session;if(!q||s.completed)throw Error('没有进行中的练习');if(s.answers[q.id])return {...s.answers[q.id],alreadySubmitted:true};choice=choice||s.selected;if(!q.options.some(o=>o.key===choice))throw Error('请先选择一个答案');const answer={choice,correct:choice===q.answer};s.answers[q.id]=answer;state.attempts.push({qid:q.id,session:s.id,...answer,time:new Date().toISOString()});if(!answer.correct)state.wrong[q.id]={corrected:false};else if(state.wrong[q.id])state.wrong[q.id].corrected=true;save();render();$('.result-line')?.scrollIntoView({block:'nearest',behavior:'smooth'});return {...answer,answer:q.answer};}
function next(){const s=state.session;if(!s||!s.answers[current()?.id])throw Error('请先提交本题答案');if(s.index===s.ids.length-1){s.completed=true;save();go('summary');}else{s.index++;s.selected=null;save();render();}window.scrollTo(0,0);return {completed:s.completed,index:s.index};}
function favorite(id){if(!byId[id])throw Error('题目不存在');const i=state.favorites.indexOf(id);if(i<0)state.favorites.push(id);else state.favorites.splice(i,1);save();render();toast(i<0?'已加入收藏':'已取消收藏');return {saved:i<0};}
function empty(title,desc,name){return `<section class="empty"><div class="tile-icon">${icon(name)}</div><h2>${title}</h2>${desc?`<p>${desc}</p>`:''}<button class="button" data-action="home">选择专项 ${icon('arrow')}</button></section>`;}
function plain(s){const d=document.createElement('div');d.innerHTML=s;return d.textContent.trim();}
function records(type){const wrong=type==='wrong';let ids=wrong?Object.keys(state.wrong):state.favorites;const all=ids.length;if(wrong&&listFilter!=='all')ids=ids.filter(id=>state.wrong[id].corrected===(listFilter==='done'));return `<h1>${wrong?'错题':'收藏'}</h1>${wrong&&all?`<div class="filters" aria-label="错题筛选">${[['all','全部'],['pending','待复习'],['done','已订正']].map(([v,l])=>`<button data-filter="${v}" class="${listFilter===v?'active':''}" aria-pressed="${listFilter===v}">${l}</button>`).join('')}</div>`:''}${ids.length?`<div class="section-heading"><span>${ids.length} 题</span><button class="button secondary" data-action="review-list" data-type="${type}">全部练习 ${icon('arrow')}</button></div><div class="records">${ids.map((id,i)=>{const q=byId[id];return `<article class="record"><span class="record-number">${String(i+1).padStart(2,'0')}</span><div class="record-text"><h3>${esc(plain(q.stem))}</h3><p>${esc(q.category)} · ${esc(q.year)} ${esc(q.region)} · ${id}</p></div><div class="record-actions">${wrong?`<span class="pill ${state.wrong[id].corrected?'done':''}">${state.wrong[id].corrected?'已订正':'待复习'}</span>`:`<button class="star-button saved" data-favorite="${id}" aria-label="取消收藏">${icon('star')}</button>`}<button class="button secondary" data-review="${id}">练习</button></div></article>`;}).join('')}</div>`:empty(wrong?(all?'无符合条件的错题':'暂无错题'):'暂无收藏','',wrong?'book':'star')}`;}
function summary(){const s=state.session;if(!s?.completed)return empty('本组尚未完成','','chart');const answers=Object.values(s.answers);return `<section class="summary-panel"><h1>本组完成</h1><p>${esc(s.title)} · ${answers.filter(a=>a.correct).length} / ${answers.length}</p><div class="summary-score">${rate(answers)}<span>%</span></div><button class="button" data-action="session-wrong" ${answers.every(a=>a.correct)?'disabled':''}>复习错题</button><button class="button secondary" data-action="home">返回专项</button></section>`;}
function render(){const page=route();const body=page==='quiz'?quiz():page==='summary'?summary():page==='wrong'||page==='favorites'?records(page):home();$('#app').innerHTML=frame(body);document.querySelectorAll('.rich img').forEach(img=>{img.tabIndex=0;img.setAttribute('role','button');});}
$('#app').addEventListener('click',e=>{const img=e.target.closest('.rich img');if(img){const clone=img.cloneNode();clone.removeAttribute('loading');$('#image-holder').replaceChildren(clone);$('#image-dialog').showModal();return;}const b=e.target.closest('button');if(!b||b.disabled)return;try{if(b.dataset.start)startGroup(b.dataset.start);else if(b.dataset.choice)choose(b.dataset.choice);else if(b.dataset.favorite)favorite(b.dataset.favorite);else if(b.dataset.review)start([b.dataset.review],'错题与收藏复习');else if(b.dataset.filter){listFilter=b.dataset.filter;render();}else switch(b.dataset.action){case'home':go('home');break;case'resume':go('quiz');break;case'submit':submit();break;case'next':next();break;case'reset':$('#reset-dialog').showModal();break;case'session-wrong':{const s=state.session;start(s.ids.filter(id=>s.answers[id]&&!s.answers[id].correct),'本组错题复习');break;}case'review-list':{let ids=b.dataset.type==='wrong'?Object.keys(state.wrong).filter(id=>listFilter==='all'||state.wrong[id].corrected===(listFilter==='done')):state.favorites;start(ids,b.dataset.type==='wrong'?'错题复习':'收藏练习');break;}}}catch(error){toast(error.message);}});
$('#app').addEventListener('toggle',e=>{if(e.target.matches('.material-panel')&&e.target.isConnected&&state.session){state.session.materialOpen=e.target.open;save();}},true);
$('#app').addEventListener('keydown',e=>{if(e.target.matches('.rich img')&&['Enter',' '].includes(e.key)){e.preventDefault();e.target.click();}});
document.addEventListener('error',e=>{if(e.target.tagName==='IMG'){const fallback=document.createElement('span');fallback.className='image-error';fallback.textContent='配图暂时无法加载。请检查本地 assets 文件夹是否完整。';e.target.replaceWith(fallback);}},true);
$('#close-image').onclick=()=>$('#image-dialog').close();$('#cancel-reset').onclick=()=>$('#reset-dialog').close();$('#confirm-reset').onclick=()=>{state=blank();save();$('#reset-dialog').close();go('home');toast('练习记录已清空');};
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);});
function registerTools(){const context=document.modelContext;if(!context?.registerTool)return;const tools=[{name:'get_practice_state',description:'读取当前练习进度和可选专项，不返回未提交题的答案。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({groups:db.groups.map(g=>({id:g.id,title:g.title,count:g.ids.length})),completedQuestions:doneIds().size,session:state.session?{title:state.session.title,index:state.session.index,count:state.session.ids.length,completed:state.session.completed}:null})},{name:'start_practice',description:'开始指定专项练习，替换当前练习进度，历史作答记录保留。',inputSchema:{type:'object',properties:{groupId:{type:'string'}},required:['groupId'],additionalProperties:false},execute:input=>startGroup(input.groupId)},{name:'submit_answer',description:'为当前题提交 A、B、C 或 D，保存作答并显示解析。',inputSchema:{type:'object',properties:{choice:{type:'string',enum:['A','B','C','D']}},required:['choice'],additionalProperties:false},execute:input=>submit(input.choice)},{name:'next_question',description:'已提交当前题后进入下一题；最后一题后显示小结。',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:next}];const controller=new AbortController();for(const tool of tools){try{Promise.resolve(context.registerTool({...tool,annotations:{readOnlyHint:false,untrustedContentHint:true,...tool.annotations}},{signal:controller.signal})).catch(()=>{});}catch{}}window.addEventListener('pagehide',()=>controller.abort(),{once:true});}
try{const response=await fetch('data/questions.json');if(!response.ok)throw Error('无法读取题库');db=await response.json();byId=Object.fromEntries(db.questions.map(q=>[q.id,q]));state.favorites=state.favorites.filter(id=>byId[id]);state.attempts=state.attempts.filter(a=>byId[a.qid]);state.wrong=Object.fromEntries(Object.entries(state.wrong).filter(([id])=>byId[id]));if(state.session&&(!Array.isArray(state.session.ids)||!state.session.ids.length||state.session.ids.some(id=>!byId[id])||!Number.isInteger(state.session.index)||state.session.index<0||state.session.index>=state.session.ids.length||!state.session.answers))state.session=null;render();registerTools();}catch(error){$('#app').innerHTML=`<main class="loading"><h1>题本暂时没有打开</h1><p>请通过本地服务器访问，并确认 data/questions.json 文件存在。</p><p>${esc(error.message)}</p><button class="button" onclick="location.reload()">重新加载</button></main>`;}
